language: android

jdk:
  - oraclejdk8

before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

android:
  components:
    - tools
    - platform-tools

notifications:
    email:
        - alessandro.crugnola@gmail.com

cache: false
sudo: false

install:
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
    - ./gradlew androidDependencies

script:
  - ./gradlew clean build lint assemble

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
